### ISSUE TITLE
Does this handle partitally ordered lists?

### ISSUE THREAD

**Issue by VaidyanathPanagar** [kalyaniuniversity/MC4#1]
I have a list of rankings `test_ranks = [['Basil', 'Carrot', 'Apple', 'Dandelion'], ['Apple', 'Basil', 'Dandelion', 'Eggs'], ['Apple', 'Fenugreek', 'Eggs', 'Dandelion']]`

Each list inside test_ranks is a ranked list. Not all the items are in all the lists. Will this package be able to handle this? If yes, how do I create a dataset with these?

**Comment by Ayan-Kumar-Saha** [comment]
Hi @VaidyanathPanagar,

No, this package doesn't handle a partially ordered list. Moreover, you need to prepare a numeric rank-based dataset in order to use this package. You can refer [here](https://github.com/kalyaniuniversity/MC4/blob/master/test_datasets/README.md) for more info on what kind of dataset this package can handle.
